#!/bin/sh
remote="$1"
PROTECTED_REMOTE="public"
PRIVATE_ITEMS="ADMIN/"

if [ "$remote" = "$PROTECTED_REMOTE" ]; then
    for item in $PRIVATE_ITEMS; do
        if [ -e "$item" ]; then
            echo "❌ ERROR: Push blocked! You cannot push to '$PROTECTED_REMOTE' while the '$item' folder exists."
            exit 1
        fi
    done
fi
exit 0
